// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq873pjdRLgXau0gHlA94vXP8W3ohGz94',
    appId: '1:434073677084:web:47d2ec27cdf78d16ecded9',
    messagingSenderId: '434073677084',
    projectId: 'atworkgo',
    authDomain: 'atworkgo.firebaseapp.com',
    storageBucket: 'atworkgo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcFZuHh96I0d8u4zwOWfIjY8CSQf-d9RU',
    appId: '1:434073677084:android:d32d8a1725b31fb2ecded9',
    messagingSenderId: '434073677084',
    projectId: 'atworkgo',
    storageBucket: 'atworkgo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_aRm5eOaD1zD9xX_lPWpIppp0XyN5tA0',
    appId: '1:434073677084:ios:b58194b386b89da8ecded9',
    messagingSenderId: '434073677084',
    projectId: 'atworkgo',
    storageBucket: 'atworkgo.firebasestorage.app',
    iosBundleId: 'com.example.atworkgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_aRm5eOaD1zD9xX_lPWpIppp0XyN5tA0',
    appId: '1:434073677084:ios:b58194b386b89da8ecded9',
    messagingSenderId: '434073677084',
    projectId: 'atworkgo',
    storageBucket: 'atworkgo.firebasestorage.app',
    iosBundleId: 'com.example.atworkgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq873pjdRLgXau0gHlA94vXP8W3ohGz94',
    appId: '1:434073677084:web:11c4067cde98614becded9',
    messagingSenderId: '434073677084',
    projectId: 'atworkgo',
    authDomain: 'atworkgo.firebaseapp.com',
    storageBucket: 'atworkgo.firebasestorage.app',
  );
}
